databases:
  - name: asas
    databaseName: asas_1zt0
    user: asas_1zt0_user

services:
  - type: web
    name: buddy
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: asas_1zt0
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false